# Generated by Django 3.2.9 on 2021-11-30 09:38

import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(blank=True, max_length=100, null=True, verbose_name='admin__id_1c')),
                ('keyword', models.CharField(max_length=100, verbose_name='admin__keyword')),
                ('show_in_filters', models.BooleanField(default=True, verbose_name='admin__show_in_filters')),
                ('name', models.CharField(max_length=100, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='admin__name')),
            ],
            options={
                'verbose_name': 'admin__attribute',
                'verbose_name_plural': 'admin__attributes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, default='default/no_image.jpg', max_length=255, verbose_name='admin__image')),
                ('image_banner', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, verbose_name='image_banner')),
                ('image_banner_uk', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, null=True, verbose_name='image_banner')),
                ('image_banner_ru', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, null=True, verbose_name='image_banner')),
                ('order', models.IntegerField(default=0, verbose_name='admin__order')),
                ('h1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__h1')),
                ('h1_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__h1')),
                ('h1_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__h1')),
                ('id_1c', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__id_1c')),
                ('link', models.CharField(max_length=255, verbose_name='URL')),
                ('link_uk', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('link_ru', models.CharField(max_length=255, null=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_uk', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__added_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='admin__update_date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='admin__parent')),
            ],
            options={
                'verbose_name': 'admin__category',
                'verbose_name_plural': 'admin__categories',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='admin__name')),
            ],
            options={
                'verbose_name': 'admin__filter',
                'verbose_name_plural': 'admin__filters',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='admin__keyword')),
                ('operation', models.CharField(choices=[('add', '+'), ('equal', '=')], max_length=20, verbose_name='admin__operation')),
                ('required', models.BooleanField(default=False, verbose_name='admin__required')),
                ('show_in_filters', models.BooleanField(default=True, verbose_name='admin__show_in_filters')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
            ],
            options={
                'verbose_name': 'admin__option',
                'verbose_name_plural': 'admin__options',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_import', models.CharField(blank=True, max_length=40, null=True, verbose_name='admin__id_import')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__article_p')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, default='default/no_image.jpg', max_length=255, verbose_name='admin__image')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='admin__price')),
                ('calc_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True, verbose_name='admin__calc_price')),
                ('lowest_option_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True)),
                ('qty', models.IntegerField(blank=True, default=1, null=True, verbose_name='admin__qty')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='admin__is_bestseller')),
                ('is_special', models.BooleanField(default=False, verbose_name='admin__is_special')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='admin__rating')),
                ('link', models.CharField(max_length=255, verbose_name='admin__link')),
                ('link_uk', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('link_ru', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_uk', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_description', models.CharField(blank=True, max_length=400, null=True, verbose_name='admin__seo_description')),
                ('seo_description_uk', models.CharField(blank=True, max_length=400, null=True, verbose_name='admin__seo_description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=400, null=True, verbose_name='admin__seo_description')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__added_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='admin__update_date')),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fk', to='products.category', verbose_name='admin__category')),
                ('show_in_categories', models.ManyToManyField(blank=True, to='products.Category', verbose_name='admin__show_in_categories')),
                ('similar', models.ManyToManyField(blank=True, related_name='_products_product_similar_+', to='products.Product', verbose_name='admin__similar')),
            ],
            options={
                'verbose_name': 'admin__product',
                'verbose_name_plural': 'admin__products',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='admin__min_amount')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__symbol_unit')),
                ('symbol_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__symbol_unit')),
                ('symbol_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__symbol_unit')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__name_unit')),
                ('name_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__name_unit')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__name_unit')),
            ],
            options={
                'verbose_name': 'admin__unit',
                'verbose_name_plural': 'admin__unit',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='admin__name')),
                ('text', models.TextField(verbose_name='admin__review')),
                ('rating', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='admin__rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='admin__is_approved')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__added_date')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='admin__product')),
            ],
            options={
                'verbose_name': 'admin__review',
                'verbose_name_plural': 'admin__reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='admin__image')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'admin__product_image',
                'verbose_name_plural': 'admin__product_images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit', verbose_name='admin__unit'),
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__id_1c')),
                ('value', models.CharField(max_length=255, verbose_name='admin__value')),
                ('value_uk', models.CharField(max_length=255, null=True, verbose_name='admin__value')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='admin__value')),
                ('option_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option', verbose_name='admin__option')),
            ],
            options={
                'verbose_name': 'admin__option_value',
                'verbose_name_plural': 'admin__option_values',
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='admin__value')),
                ('value_uk', models.CharField(max_length=255, null=True, verbose_name='admin__value')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='admin__value')),
                ('filter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filter', verbose_name='admin__filter')),
            ],
            options={
                'verbose_name': 'admin__filter_value',
                'verbose_name_plural': 'admin__filters_values',
            },
        ),
        migrations.CreateModel(
            name='FilterOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filter', verbose_name='admin__filter')),
                ('filter_value_fk', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='filter_fk', chained_model_field='filter_fk', on_delete=django.db.models.deletion.CASCADE, to='products.filtervalue', verbose_name='admin__filter_value')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='admin__product')),
            ],
            options={
                'verbose_name': 'admin__filter_of_product',
                'verbose_name_plural': 'admin__filters_of_products',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='admin__start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 12, 1, 11, 38, 50, 425276), verbose_name='admin__end_date')),
                ('type', models.CharField(choices=[('percentage', 'products__discount_with_percantage'), ('sum', 'products__discount_with_sum')], max_length=255, verbose_name='admin__type')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='admin__value')),
                ('product_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='admin__product')),
            ],
            options={
                'verbose_name': 'admin__discount',
                'verbose_name_plural': 'admin__discounts',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(blank=True, max_length=100, null=True, verbose_name='admin__id_1c')),
                ('value', models.CharField(max_length=100, verbose_name='admin__value')),
                ('value_uk', models.CharField(max_length=100, null=True, verbose_name='admin__value')),
                ('value_ru', models.CharField(max_length=100, null=True, verbose_name='admin__value')),
                ('attribute_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='admin__attribute')),
            ],
            options={
                'verbose_name': 'admin__attribute_value',
                'verbose_name_plural': 'admin__attributes_values',
            },
        ),
        migrations.CreateModel(
            name='OptionOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='admin__qty')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True, verbose_name='admin__price')),
                ('option_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option', verbose_name='admin__option')),
                ('option_value_fk', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='option_fk', chained_model_field='option_fk', on_delete=django.db.models.deletion.CASCADE, to='products.optionvalue', verbose_name='admin__option_value')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='admin__product')),
            ],
            options={
                'verbose_name': 'admin__option_of_product',
                'verbose_name_plural': 'admin__options_of_products',
                'unique_together': {('option_fk', 'product_fk', 'option_value_fk')},
            },
        ),
        migrations.CreateModel(
            name='AttributeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='admin__attribute')),
                ('attribute_value_fk', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='attribute_fk', chained_model_field='attribute_fk', on_delete=django.db.models.deletion.CASCADE, to='products.attributevalue', verbose_name='admin__attribute_value')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='admin__product')),
            ],
            options={
                'verbose_name': 'admin__attribute_of_product',
                'verbose_name_plural': 'admin__attributes_of_products',
                'unique_together': {('attribute_fk', 'product_fk')},
            },
        ),
    ]
