# Generated by Django 3.2.9 on 2021-12-01 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 15, 47, 39, 503768), verbose_name='admin__end_date'),
        ),
    ]
