# Generated by Django 3.2.9 on 2021-12-01 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 16, 5, 53, 464115), verbose_name='admin__end_date'),
        ),
    ]
