# Generated by Django 3.2.9 on 2021-12-02 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 16, 55, 4, 23535), verbose_name='admin__end_date'),
        ),
    ]
