# Generated by Django 3.2.9 on 2021-12-04 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 18, 19, 22, 920373), verbose_name='admin__end_date'),
        ),
    ]
