# Generated by Django 3.2.9 on 2021-12-06 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 27, 7, 493918), verbose_name='admin__end_date'),
        ),
    ]
