# Generated by Django 3.2.9 on 2022-02-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_discount_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active_in_mainpage',
            field=models.BooleanField(default=False, verbose_name='Відображення на головній '),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 15, 59, 54, 93006), verbose_name='admin__end_date'),
        ),
    ]
