# Generated by Django 3.2.9 on 2022-02-05 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20220205_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 16, 2, 29, 465972), verbose_name='admin__end_date'),
        ),
    ]
