# Generated by Django 3.2.9 on 2022-02-05 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 16, 3, 47, 214855), verbose_name='admin__end_date'),
        ),
    ]
