# Generated by Django 3.2.9 on 2021-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='admin__name_form_form_request')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='admin__country')),
                ('cooperation_type', models.CharField(blank=True, max_length=255, verbose_name='admin__cooperation_type')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='admin__phone')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='admin__email')),
                ('comment', models.TextField(blank=True, verbose_name='admin__comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='admin__date')),
            ],
            options={
                'verbose_name': 'admin__form_request',
                'verbose_name_plural': 'admin__forms_request',
            },
        ),
    ]
