# Generated by Django 3.2.9 on 2021-11-30 09:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.IntegerField(default=0, verbose_name='admin__items_count')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='admin__total_price')),
            ],
            options={
                'verbose_name': 'admin__cart',
                'verbose_name_plural': 'admin__carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='admin__qty')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='admin__total_price')),
                ('stable_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='admin__total_price')),
            ],
            options={
                'verbose_name': 'admin__cart_item',
                'verbose_name_plural': 'admin__cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='admin__first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='admin__last_name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='admin__phone')),
                ('delivery_settlement', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__delivery_settlement')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__delivery_address')),
                ('post_index', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__post_index')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='admin__email')),
                ('delivery_type', models.CharField(choices=[('pickup', 'pickup'), ('new_post', 'new_post'), ('avtoluks', 'avtoluks'), ('in_time', 'in_time'), ('delivery', 'delivery'), ('ukr_post', 'ukr_post')], max_length=255, verbose_name='admin__delivery_type')),
                ('payment_type', models.CharField(choices=[('cod', 'cod'), ('liqpay', 'liqpay')], max_length=255, verbose_name='admin__payment_type')),
                ('comment', models.TextField(blank=True, verbose_name='admin__comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='admin__date')),
                ('currency_data', models.TextField(blank=True, verbose_name='admin__currency_data')),
                ('is_paid', models.BooleanField(default=False, verbose_name='admin__is_paid')),
                ('is_one_click_order', models.BooleanField(default=False, verbose_name='admin__is_one_click_order')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='admin__total')),
            ],
            options={
                'verbose_name': 'admin_order_model',
                'verbose_name_plural': 'admin_orders_model',
            },
        ),
        migrations.CreateModel(
            name='OrderMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('new', 'order_status__new'), ('canceled', 'order_status__canceled'), ('pending', 'order_status__pending'), ('sent', 'order_status__sent'), ('completed', 'order_status__completed')], max_length=255, unique=True, verbose_name='admin__status')),
                ('text', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='admin__text')),
                ('subject', models.CharField(max_length=255, verbose_name='admin__subject')),
            ],
            options={
                'verbose_name': 'admin__order_message_template',
                'verbose_name_plural': 'admin__orders_message_templates',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('new', 'order_status__new'), ('canceled', 'order_status__canceled'), ('pending', 'order_status__pending'), ('sent', 'order_status__sent'), ('completed', 'order_status__completed')], default=('new', 'order_status__new'), max_length=255, verbose_name='admin__order_code')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='admin__date')),
                ('notify_user', models.BooleanField(default=True, verbose_name='admin_notify_user')),
                ('order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order', verbose_name='admin_order_fk')),
            ],
            options={
                'verbose_name': 'admin__order_status',
                'verbose_name_plural': 'admin__orders_status',
            },
        ),
    ]
