# Generated by Django 3.2.9 on 2021-11-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='admin__user'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option_of_product_mtm',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='product_fk', chained_model_field='product_fk', related_name='option_of_product_mtm', to='products.OptionOfProduct'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order', verbose_name='admin__product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='admin__product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='checkout.CartItem', verbose_name='admin__items'),
        ),
    ]
