# Generated by Django 3.2.9 on 2021-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='admin__order')),
                ('keyword', models.CharField(blank=True, choices=[('footer', 'Показывать в футере'), ('contacts', 'Отображать на странице контактов')], default=None, max_length=255, verbose_name='admin__keyword_contacts')),
                ('address', models.CharField(blank=True, default=None, max_length=150, verbose_name='admin__address')),
                ('address_uk', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='admin__address')),
                ('address_ru', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='admin__address')),
            ],
            options={
                'verbose_name': 'admin__address',
                'verbose_name_plural': 'admin__addresses',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, choices=[('footer', 'Показывать в футере'), ('contacts', 'Отображать на странице контактов'), ('checkout', 'Оповещения о новых заказах'), ('feedback_form', 'Зворотній звязок')], default=None, max_length=64, verbose_name='admin__keyword_contacts')),
                ('email', models.CharField(blank=True, default=None, max_length=100, verbose_name='admin__email')),
            ],
            options={
                'verbose_name': 'admin__email',
                'verbose_name_plural': 'admin__emails',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=100, verbose_name='admin__phone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='admin__order')),
                ('keyword', models.CharField(blank=True, choices=[('footer', 'Показывать в футере'), ('contacts', 'Отображать на странице контактов')], max_length=40, null=True, verbose_name='admin__keyword_contacts')),
            ],
            options={
                'verbose_name': 'admin__phone',
                'verbose_name_plural': 'admin__phones',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, default=None, max_length=100, verbose_name='admin__keyword_contacts')),
                ('link', models.CharField(blank=True, default=None, max_length=100, verbose_name='admin__link_social_network')),
            ],
            options={
                'verbose_name': 'admin__social_network',
                'verbose_name_plural': 'admin__social_networks',
            },
        ),
    ]
