# Generated by Django 3.2.9 on 2021-11-30 09:38

import ckeditor_uploader.fields
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_marker', models.CharField(blank=True, default=None, max_length=255, verbose_name='admin__name_marker')),
                ('lat', models.FloatField(max_length=20, verbose_name='admin__lng')),
                ('longitude', models.FloatField(max_length=20, verbose_name='admin__longitude')),
            ],
            options={
                'verbose_name': 'admin__google_map',
                'verbose_name_plural': 'admin__google_map',
            },
        ),
        migrations.CreateModel(
            name='SeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, choices=[('mainpage', 'Главная Страница'), ('blog', 'Блог'), ('catalog', 'Каталог'), ('contacts', 'Контакты'), ('reviews', 'Отзывы')], default=None, max_length=255, unique=True, verbose_name='admin__keyword')),
                ('seo_title', models.CharField(max_length=255, verbose_name='admin__title')),
                ('seo_title_uk', models.CharField(max_length=255, null=True, verbose_name='admin__title')),
                ('seo_title_ru', models.CharField(max_length=255, null=True, verbose_name='admin__title')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('seo_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='admin__description')),
            ],
            options={
                'verbose_name': 'admin__seo_data',
                'verbose_name_plural': 'admin__seo_data',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Another Shop', max_length=20, verbose_name='admin__name')),
                ('logo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='admin__logo')),
                ('favicon', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='fav_icon')),
                ('robots_txt', models.TextField(blank=True, default='', null=True, verbose_name='Robots.txt')),
                ('sitemap', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=255, null=True, verbose_name='Sitemap')),
                ('google_analytics_code', models.TextField(blank=True, default='', null=True, verbose_name='admin__google_analytics')),
                ('formula_for_seo_generation_title', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_title')),
                ('formula_for_seo_generation_title_uk', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_title')),
                ('formula_for_seo_generation_title_ru', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_title')),
                ('formula_for_seo_generation_description', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_description')),
                ('formula_for_seo_generation_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_description')),
                ('formula_for_seo_generation_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='formula_for_seo_generation_description')),
            ],
            options={
                'verbose_name': 'admin__settings',
                'verbose_name_plural': 'admin__settings',
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, choices=[('ua_production', 'Главная - Украинское производство'), ('mission_1', 'Главная - Миссия'), ('mission_2', 'Главная - Видение'), ('retail_districts', 'Розничным - Список областей'), ('mainpage_h1', 'Главная - H1')], default=None, max_length=255, unique=True, verbose_name='admin__keyword')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='admin__title')),
                ('title_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__title')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
            ],
            options={
                'verbose_name': 'admin__text_content',
                'verbose_name_plural': 'admin__text_contents',
            },
        ),
    ]
