# Generated by Django 3.2.9 on 2021-11-30 09:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='admin__order')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('link', models.CharField(max_length=255, verbose_name='admin__link')),
                ('link_uk', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('link_ru', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_title')),
                ('seo_title_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_title')),
                ('seo_title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_title')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='meta_description')),
                ('seo_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='meta_description')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='meta_description')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__added_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='admin__update_date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='custom_page.custompage', verbose_name='admin__parent')),
            ],
            options={
                'verbose_name': 'admin__custom_page',
                'verbose_name_plural': 'admin__custom_pages',
            },
        ),
    ]
