# Generated by Django 3.2.9 on 2021-11-30 09:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='admin__image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='admin__order')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('link', models.CharField(max_length=255, verbose_name='admin__link')),
                ('link_uk', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('link_ru', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__title')),
                ('seo_title_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__title')),
                ('seo_title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__title')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__description')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__added_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='admin__update_date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='admin__parent')),
            ],
            options={
                'verbose_name': 'admin__category',
                'verbose_name_plural': 'admin__categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='admin__article_image')),
                ('image_uk', filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='admin__article_image')),
                ('image_ru', filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='admin__article_image')),
                ('active', models.BooleanField(default=True, verbose_name='admin__article_active')),
                ('link', models.CharField(max_length=255, verbose_name='admin__link')),
                ('link_uk', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('link_ru', models.CharField(max_length=255, null=True, verbose_name='admin__link')),
                ('name', models.CharField(max_length=255, verbose_name='admin__name')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='admin__name')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_uk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='admin__seo_title')),
                ('seo_description', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('seo_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='admin__seo_description')),
                ('short_description', models.TextField(blank=True, default='', null=True, verbose_name='admin__short_content')),
                ('short_description_uk', models.TextField(blank=True, default='', null=True, verbose_name='admin__short_content')),
                ('short_description_ru', models.TextField(blank=True, default='', null=True, verbose_name='admin__short_content')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__content')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__content')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='admin__content')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='admin__article_added_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='admin__article_update_date')),
                ('category_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='blog.category', verbose_name='admin__article_category')),
                ('show_in_categories', models.ManyToManyField(blank=True, related_name='show_in_categories', to='blog.Category', verbose_name='admin__article_show_in_categories')),
            ],
            options={
                'verbose_name': 'admin__article',
                'verbose_name_plural': 'admin__articles',
            },
        ),
    ]
