# Generated by Django 3.2.9 on 2021-11-30 09:38

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('mainpage', 'admin__mainpage')], max_length=255, unique=True, verbose_name='admin__keyword')),
                ('overlay_opacity', models.CharField(blank=True, default='0', max_length=10, verbose_name='admin__overlay_opacity')),
                ('overlay_color', models.CharField(max_length=255, verbose_name='admin__overlay_color')),
                ('content_position', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], max_length=255, verbose_name='admin__content_position')),
                ('content_color', models.CharField(blank=True, max_length=255, verbose_name='admin__content_color')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='admin__image')),
                ('image_uk', filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='admin__image')),
                ('image_ru', filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='admin__image')),
                ('content_text', models.CharField(blank=True, max_length=255, verbose_name='admin__content_text')),
                ('content_text_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__content_text')),
                ('content_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__content_text')),
                ('button_text', models.CharField(blank=True, max_length=255, verbose_name='admin__button_text')),
                ('button_text_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__button_text')),
                ('button_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__button_text')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='admin__button_link')),
                ('button_link_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__button_link')),
                ('button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='admin__button_link')),
            ],
            options={
                'verbose_name': 'admin__banner_model',
                'verbose_name_plural': 'admin__banners_model',
            },
        ),
    ]
