# Generated by Django 3.2.9 on 2021-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='keyword',
            field=models.CharField(choices=[('mainpage', 'admin__mainpage')], max_length=255, unique=True, verbose_name='admin__keyword'),
        ),
    ]
