# Generated by Django 3.2.9 on 2021-12-04 16:32

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_banner_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('mainpage', 'admin__mainpage')], max_length=255, unique=True, verbose_name='admin__keyword')),
                ('active', models.BooleanField(default=True, verbose_name='admin__active')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='admin__image')),
                ('content_text', models.CharField(blank=True, max_length=255, verbose_name='admin__content_text')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='admin__button_link')),
            ],
            options={
                'verbose_name': 'admin__banner_model',
                'verbose_name_plural': 'admin__banners_model',
            },
        ),
    ]
