# Generated by Django 3.2.9 on 2021-12-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_banner_second'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner_second',
        ),
    ]
